# Generated by Django 3.1.2 on 2020-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malignancyPrediction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_by', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=30)),
            ],
        ),
    ]
