# Generated by Django 3.1.2 on 2020-10-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malignancyPrediction', '0002_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
